#
# global theme settings
#

languages:
- lang: en
  title: English
- lang: de
  title: Deutsch
- lang: zh-hk
  title: 香港繁體

# stylesheets loaded in the <head>
stylesheets:
- /index.css

# scripts loaded in the end of the body
scripts:
- /index.js
